server:
  port: 8888

spring:
  application:
    name: SPRING-CLOUD-SERVICE
  cloud:
    config:
      server:
        git:
          uri: file:///C:\Users\taomish\my_data\spring_boot\in28min\git-config-repo

