server:
  port: 8978

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: department
          uri: lb://department
          predicates:
            - Path=/department/**
          filters:
            - name: CircuitBreaker
              args:
                name: department
                fallbackuri: forward:/departmentFallBack
        - id: user
          uri: lb://user
          predicates:
            - Path=/user/**
          filters:
            - name: CircuitBreaker
              args:
                name: user
                fallbackuri: forward:/userFallBack

#hystrix:
#  command:
#    fallbackcmd:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 4000

#management:
#  endpoints:
#    web:
#      exposure:
#        include: hystrix.stream
