server:
  port: 8978

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders:
              - content-type
              - Authorization
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/user/**
        - id: CALL-CENTER-SERVICE
          uri: lb://CALL-CENTER-SERVICE
          predicates:
            - Path=/api/center/**,/api/chart/**,/api/task/**,/api/yojana/**,/center,/api/pincode/**

#hystrix:
#  command:
#    fallbackcmd:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 4000

#management:
#  endpoints:
#    web:
#      exposure:
#        include: hystrix.stream
