server:
  port: 9004

spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/resolved
    username: root
    spring.datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: USER-SERVICE
  mail:
    host: smtp.gmail.com
    port: 587
    username: mpandeyji2018@gmail.com
    password: umyavmfnztqgilty
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


twilio:
  account_sid: AC95cefe7574f079ce93b89410aba63e0a
  auth_token: 1711332097f9beaf0c0324e6c25d6e7d
  trail_number: +18593507447


eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka



